spring:
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always

logging.level:
  org.springframework.orm.jpa: INFO
  org.springframework.transaction: INFO
  ru.practicum.ewm: DEBUG

server:
  port: 0

ewm:
  timeout:
    admin: PT1H
    user: PT2H
---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/events
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-dev
    username: dev
    password: dev