server:
  port: 0

spring:
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always

logging.level:
  org.springframework.orm.jpa: INFO
  org.springframework.transaction: INFO

---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/ewm_stats
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm_stats
    username: stats
    password: stats