spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/ewm_stats
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always

logging.level:
  org.springframework.orm.jpa: INFO
  org.springframework.transaction: INFO

server.port: 0