server:
  port: 0

kafka:
  topic:
    actions: stats.user-actions.v1
    similarity: stats.events-similarity.v1
  bootstrap-server: localhost:9092
  group-id: aggregator

logging:
  level:
    ru.practicum: debug
    root: info