spring:
  application:
    name: gateway-server
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 10000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true